wespeaker/bin/export_jit.py, wespeaker/bin/extract.py, wespeaker/bin/train.py, wespeaker/models/__init__.py, wespeaker/models/ecapa_tdnn.py, wespeaker/models/pooling_layers.py, wespeaker/models/resnet.py, wespeaker/models/speaker_model.py, wespeaker/models/tdnn.py, wespeaker/utils/utils.py
[fix] fix some errors in Lint.
=> Hongji flake8

wespeaker/bin/extract.py, wespeaker/bin/score.py, wespeaker/bin/train.py, wespeaker/dataset/dataset.py, wespeaker/models/ecapa_tdnn.py, wespeaker/models/pooling_layers.py, wespeaker/models/projections.py, wespeaker/models/resnet.py, wespeaker/models/tdnn.py
=> [lint] fix flake8 lint error.

wespeaker/utils/dataset_utils.py
wespeaker/utils/dataset_utils.py:    remove time warp in spec_aug
=> [fix] remove time warp in spec_aug

examples/voxceleb/v2/run.sh, wespeaker/bin/compute_det.py, wespeaker/utils/score_metrics.py
=> [wespeaker] add code for plotting det curve

examples/voxceleb/v2/local/extract_vox.sh, examples/voxceleb/v2/run.sh, tools/extract_embedding.sh
Before:
$nj = 4 (no more than the number of gpu in local machine)
then, gpu_id: 0,1,2,3
Now:
$nj = 6, gpus= [0,2]
then, gpu_id: 0,2,0,2,0,2
=> [extract] change multi-process

examples/voxceleb/v2/.run_shards.sh, examples/voxceleb/v2/conf/uio.yaml, tools/make_lmdb.py, tools/make_shard_list.py, wespeaker/bin/train_uio.py, wespeaker/dataset/lmdb_data.py, wespeaker/dataset/processor.py, wespeaker/dataset/udataset.py, wespeaker/utils/file_utils.py
The whole processing pipeline.
1. All the training data are packed to `shard`
2. noise/reverb are packed in LMDB
1. why `shard` for training data:  the production-scale speech dataset is over tens of thousands of hours speech
2. why `LMDB` for noise/reverb: typically noise and reverb are limited, LMDB helps to pack them and do random access.
=> [dataset] add shard io

examples/voxceleb/v2/local/score.sh, examples/voxceleb/v2/local/score_norm.sh, examples/voxceleb/v2/run.sh, examples/voxceleb/v2/run_shards.sh, tools/vector_mean.py, wespeaker/utils/score_norm.py
| Model | backend | Params | vox1-O(%)    | minDCF(0.01) | vox1-E(%)   | minDCF(0.01) | vox1-H(%)     | minDCF(0.01) |
|:------|--------|-----------|----------|------------|------------|------------|------------|------------|
| ResNet34-TSTP-emb256-UIO | cosine           | 6.70M  | 1.005     | 0.092        | 1.134     | 0.122        | 1.984     | 0.194        |
| ResNet34-TSTP-emb256-UIO | cosine+asnorm100 | 6.70M  | 0.952     | 0.087        | 1.074     | 0.113        | 1.846     | 0.175        |
| ECAPA_TDNN_GLOB_c512-ASTP-emb192-UIO | cosine | 6.19M | 1.213 | 0.129 | 1.234 | 0.140 | 2.334 | 0.222 |
| ECAPA_TDNN_GLOB_c512-ASTP-emb192-UIO | cosine+asnorm100 | 6.19M | 1.037 | 0.126 | 1.150 | 0.128 | 2.094 | 0.201 |
=> [wespeaker] add as-norm

examples/voxceleb/v2/local/score_norm.sh, examples/voxceleb/v2_deprecated/local/score_norm.sh, wespeaker/utils/score_norm.py
=> [norm] refine the split_embedding function

examples/cnceleb/v2/local/extract_cnc.sh, examples/cnceleb/v2/local/format_trials_cnceleb.py, examples/cnceleb/v2/local/prepare_data.sh, examples/cnceleb/v2/run.sh
The test results are as follows:
Due to the change of data IO, the model needs to be retrained later.
=> [examples] add multi-enroll test in cnceleb recipe

runtime/server/x86_gpu/README.md, wespeaker/bin/export_onnx.py
Signed-off-by: slyne deng <slyned@nvidia.com>
=> fix gpu export based on new onnx export

README.md, ROADMAP.md
Fix the link error of papers.md and update the current progress.
=> [docs] update README.md and ROADMAP.md

examples/voxceleb/v2/README.md, examples/voxceleb/v2/local/score_plda.sh, wespeaker/bin/compute_det.py
update bin/compute_det.py as well
=> [plda] update plda scripts

examples/cnceleb/v2/local/choose_utts_to_combine.py
Previous combine:
Current combine:
=> [examples] fix combine short utterance bug

.flake8, examples/cnceleb/v2/local/download_data.sh, examples/voxceleb/v2/local/prepare_data.sh, examples/voxceleb/v2_deprecated/local/prepare_data.sh
see https://github.com/wenet-e2e/wespeaker/issues/120
=> [fix] fix some bugs and flake8 lint problem

runtime/binding/python/README.md, runtime/binding/python/py/__init__.py, runtime/binding/python/py/inference.py, runtime/binding/python/py/speaker.py, runtime/binding/python/setup.py
1. Add new api:
- compute_cosine_score
- extract_embedding_feat
2. Rename `Inference` to `Speaker`.
=> [binding] add new api and refine codes

wespeaker/utils/checkpoint.py
=> [fix] fix the problem that checkpoint loading cause out of memory

wespeaker/dataset/processor.py
=> [uio] fix the bug of loading network shard files

wespeaker/dataset/dataset.py
=> [fix] fix the filter processor, which should be only used in the training process

examples/cnceleb/v2/conf/ecapa_tdnn.yaml, examples/cnceleb/v2/conf/ecapa_tdnn_lm.yaml, examples/cnceleb/v2/conf/repvgg.yaml, examples/cnceleb/v2/conf/resnet.yaml, examples/cnceleb/v2/conf/resnet_lm.yaml, examples/voxceleb/v2/conf/campplus.yaml, examples/voxceleb/v2/conf/campplus_lm.yaml, examples/voxceleb/v2/conf/ecapa_tdnn.yaml, examples/voxceleb/v2/conf/ecapa_tdnn_lm.yaml, examples/voxceleb/v2/conf/repvgg.yaml, examples/voxceleb/v2/conf/resnet.yaml, examples/voxceleb/v2/conf/resnet_lm.yaml, examples/voxceleb/v2/conf/xvec.yaml, examples/voxceleb/v2/conf/xvec_lm.yaml, wespeaker/bin/train.py, wespeaker/dataset/dataset.py, wespeaker/utils/executor.py
=> [uio] Support manually specifying the number of samples traversed in each epoch

.gitignore, README.md, ROADMAP.md, docs/python_package.md, wespeaker/cli/speaker.py
[doc] Move supported list from ReadMe to RoadMap
[feature] Add support to extract kaldi-style embeddings from wav.scp, save to ark/scp
=> add kaldi-style embedding extraction for CLI

README.md
modelscope demo: https://www.modelscope.cn/studios/wenet/Speaker_Verification_in_WeSpeaker/summary
=> [doc] modelscope demo

README.md, docs/README.md, docs/contribute.md, docs/pretrained.md, docs/python_package.md, docs/speaker_recognition_papers.md, docs/vox.md, docs/vox_ssl.md
Add documents for supervised/self-supervised learning and .etc.
=> [docs] update the documents

wespeaker/cli/speaker.py
Add a function `extract_embedding_from_pcm` such that we can easily extract speaker embedding from part of a long wav file, as well as other formats than wav.
=> Add a function `extract_embedding_from_pcm`

wespeaker/cli/speaker.py
使用hamming窗。
其他改动是pre-commit 自动lint
=> [cli] Using Hanming Window

wespeaker/cli/speaker.py
Support setting window types. Cam++ and eres2net of damo use Povey window.
=> [cli] support setting window_type
