wenet-e2e/wespeaker

- examples/voxceleb/v2/conf/ecapa_tdnn.yaml
- examples/voxceleb/v2/conf/resnet.yaml
- examples/voxceleb/v2/conf/xvec.yaml
- examples/voxceleb/v2/run.sh
- wespeaker/bin/train.py
1. Add "margin_scheduler" variable in config.yaml
2. Remove "add num_epochs according to aug_prob" in wespeaker/bin/train.py
3. Do not initialize the projection layer for model_init
> [wespeaker] Refine wespeaker codes.

- wespeaker/bin/average_model.py
Use epoch to rank models.
If the model is sorted by creation time, the sorting may be wrong when copying the model file to another location.
> [bin] use epoch to rank models

- examples/cnceleb/v2/conf/ecapa_tdnn.yaml
- examples/cnceleb/v2/conf/ecapa_tdnn_lm.yaml
- examples/cnceleb/v2/conf/repvgg.yaml
- examples/cnceleb/v2/conf/resnet.yaml
- examples/cnceleb/v2/conf/resnet_lm.yaml
- examples/voxceleb/v2/conf/ecapa_tdnn.yaml
- examples/voxceleb/v2/conf/ecapa_tdnn_lm.yaml
- examples/voxceleb/v2/conf/repvgg.yaml
- examples/voxceleb/v2/conf/resnet.yaml
- examples/voxceleb/v2/conf/resnet_lm.yaml
- examples/voxceleb/v2/conf/xvec.yaml
- examples/voxceleb/v2/conf/xvec_lm.yaml
- wespeaker/bin/train.py
- wespeaker/models/pooling_layers.py
- wespeaker/models/projections.py
- wespeaker/utils/executor.py
Should I add some comment about this update at somewhere?
> [wespeaker] add automatic mixed precision training

- requirements.txt
I am new to wespeaker and thanks in advance for your work!
When I was configuring the environment, I found for CN-Celeb, torchaudio is essential for data preparation, so I would like to add it in requirements.txt.
Also, the current version of onnxruntime cannot be found in conda, so I remove the version specification.
> remove ort version on requirements.txt

- wespeaker/bin/train.py
Compare the log between multi-node and single-node training (above single node):
To train the code on multi-node, we can directly change the line 
torchrun --standalone --nnodes=1 --nproc_per_node=$num_gpus
in run.sh to
torchrun --nnodes $node_num --nproc_per_node $num_process_per_node --rdzv_backend=c10d
> [fix] fix rank setup, solve the problem that multiple processes cannot be started, test multi-node training

- README.md
- runtime/core/speaker/e2e_speaker.cc
- runtime/core/speaker/onnx_speaker_model.cc
- runtime/core/speaker/onnx_speaker_model.h
- runtime/onnxruntime/README.md
1. RTF
> num_threads = 1
>
> SamplesPerChunk = 80000
>
> CPU: Intel(R) Xeon(R) Platinum 8160 CPU @ 2.10GHz
| Model              | RTF       |
| ------------------ | --------- |
| ResNet-34          | 0.060735  |
| ECAPA-TDNN (C=512) | 0.0183512 |
2. EER (%)
> onnxruntime: SamplesPerChunk=-1.
>
> don't use mean normalization for evaluation embeddings.
| Model          | vox-O | vox-E | vox-H |
| -------------- | ----- | ----- | ----- |
| ResNet-34-pt   | 0.814 | 0.933 | 1.679 |
| ResNet-34-onnx | 0.814 | 0.933 | 1.679 |
> [runtime] update onnxruntime benchmark results and README.md

- wespeaker/dataset/processor.py
function `get_random_chunk` is called in `add_reverb_noise` with numpy.narray as input(`data`). However, `Tensor.repeat` is different from `numpy.repeat`. Maybe `numpy.tile` is what you want.
> [processor.py] fix bugs when get_random_chunk input is numpy.narray

- README.md
- examples/voxceleb/v2/README.md
- examples/voxceleb/v2/conf/resnet.yaml
- wespeaker/models/projections.py
- wespeaker/utils/executor.py
- wespeaker/utils/executor_deprecated.py
> [loss] add sphereface2 loss function

- README.md
- ROADMAP.md
- examples/sre/v2/README.md
- examples/sre/v2/local/score_plda.sh
- examples/sre/v2/run.sh
- examples/voxceleb/v2/README.md
- examples/voxceleb/v2/local/score_plda.sh
- wespeaker/bin/adapt_plda.py
- wespeaker/bin/average_model.py
- wespeaker/bin/compute_metrics.py
- wespeaker/bin/eval_plda.py
- wespeaker/bin/export_jit.py
- wespeaker/bin/export_onnx.py
- wespeaker/bin/extract.py
- wespeaker/bin/extract_deprecated.py
- wespeaker/bin/infer_onnx.py
- wespeaker/bin/score.py
- wespeaker/bin/score_norm.py
- wespeaker/bin/train.py
- wespeaker/bin/train_deprecated.py
- wespeaker/bin/train_plda.py
- wespeaker/utils/plda/kaldi_utils.py
- wespeaker/utils/plda/plda_utils.py
- wespeaker/utils/plda/two_cov_plda.py
- wespeaker/utils/utils.py
We update the PLDA code to be compatible with Kaldi version, and the related unsupervised domain adaptation codes. This is super important for the SRE recipe where COS scoring doesn't work well.
> Update the PLDA code

- runtime/core/speaker/onnx_speaker_model.cc
- runtime/core/speaker/speaker_engine.cc
- runtime/core/utils/utils.cc
- runtime/core/utils/utils.h
目前windows 编译有2个错误：
1.  SpeakerEngine::CosineSimilarity 这个函数中 使用std::inner_product 错误，windows 上没有引用正确的头文件，[inner_product](https://en.cppreference.com/w/cpp/algorithm/inner_product)  正确的头文件是` #include <numeric>`
2. windows 上 onnxruntime  创建 Ort::Session 的参数错误，对应到如下代码：
```
speaker_session_ = std::make_shared<Ort::Session>(env_, model_path.c_str(),
session_options_);
```
按照 https://github.com/wenet-e2e/wenet/blob/a7931ac212c4f28112874ca80cde3588ffedda4e/runtime/core/decoder/onnx_asr_model.cc#L86  这里修改 增加了  ToWString 转换函数
> fix windows build error

- wespeaker/cli/fbank.py
- wespeaker/cli/speaker.py
https://github.com/ZitengWang/python_kaldi_features
> [cli] produce the same results as with torchaudio.compliance.kaldi

- README.md
extract_embeding function is not defined, should be changed to extract_embedding (tested)
Removed the python binding related description in readme since it's removed
> [doc] fix the cli command readme, remove python binding

- docs/python_package.md
- wespeaker/__init__.py
- wespeaker/cli/speaker.py
In some cases, we don't want to use the provided version in hugging face:
1) use models in the pretrained page
2) use the models trained by the userself
Add a --pretrain flag to the cli command, if this is speficied, the model will be loaded from a local path.
> [feature] cli support for pretrained model locally

- wespeaker/cli/speaker.py
bug fix
model.recognize 方法中 best_score 需要小于 score
将 best_name 最终赋值给 result['name']  
#236
> model.recognize 方法中 best_score 需要小于 score

- requirements.txt
https://github.com/wenet-e2e/wespeaker/blob/1baf64260d54f41d64931170409a8355e38524f5/wespeaker/__init__.py#L1-L2
这两行代码调用了cli部分
> [doc] add silero-vad package

- .pre-commit-config.yaml
- README.md
- requirements.txt
Follow: https://github.com/wenet-e2e/wenet/pull/2197 https://github.com/wenet-e2e/wenet/pull/2195 https://github.com/wenet-e2e/wenet/pull/2198
> [lint] use pre-commit to auto check and lint

- .gitignore
- examples/voxconverse/v2/diar/extract_emb.py
- examples/voxconverse/v2/diar/make_rttm.py
- examples/voxconverse/v2/diar/spectral_clusterer.py
- wespeaker/cli/speaker.py
- wespeaker/cli/utils.py
- wespeaker/utils/cluster.py
- wespeaker/utils/diar_utils.py
```wespeaker --task diarization --audio_file /Users/user01/Downloads/voxconverse_test_wav/aepyx.wav  --language english```
> [cli] support diar

- runtime/core/frontend/wav.h
bug描述：对于正常的PCM数据，读取的二进制数据大小应该是偶数。但对于异常数据，读取的二进制数据大小是奇数，那么就是发生越界问题。
> [runtime] fix bug in PcmReader where data may be out of bounds

- wespeaker/cli/hub.py
- wespeaker/cli/speaker.py
- wespeaker/cli/utils.py
- wespeaker/models/eres2net.py
usags:
```bash 
wespeaker --eres2net --task embedding --audio_file ../1000003_0f90da0d.wav --output_file test.txt
wespeaker --campplus --task embedding --audio_file ../1000003_0f90da0d.wav --output_file test.txt
```
> [cli] support campplus_200k and eres2net_200k models of damo

- docs/README.md
- docs/contribute.md
- docs/index.rst
- docs/paper.md
- docs/pretrained.md
- docs/python_package.md
- docs/runtime.md
- docs/speaker_recognition_papers.md
- docs/train.rst
- docs/vox.md
- docs/vox_ssl.md
- docs/voxconverse_diar.md
- examples/voxconverse/v1/run.sh
- examples/voxconverse/v2/run.sh
also fix some minor errors ...
> [docs] add diarization tutorial in doc and re-order the directory structure in the index page

- runtime/core/speaker/speaker_engine.cc
当我在windows下用MSVC编译，在运行时出现和 #205 一样的问题。经过排查发现 `chunk_feat` 长度为178 , 而`num_chunk_frames_` (使用默认参数)为198. 所有vector索引越界了。
另外我使用 #205 问题中的音频是没有问题的，我是使用自己的音频(不到1s)。
> [fix] cannot seek vector iterator after end

- README.md
- examples/cnceleb/v2/README.md
- examples/cnceleb/v2/local/score_calibration.sh
- examples/cnceleb/v2/run.sh
- examples/voxceleb/v2/README.md
- examples/voxceleb/v2/local/score_calibration.sh
- examples/voxceleb/v2/run.sh
- tools/generate_calibration_trial.py
- wespeaker/bin/compute_det.py
- wespeaker/bin/compute_metrics.py
- wespeaker/bin/score_calibration.py
- wespeaker/bin/score_norm.py
We support score calibration for Voxceleb recipe, and the results are listed as following:
ResNet34
ResNet34 LM
ResNet293 LM
ECAPA_TDNN1024 LM
We support score calibration for Cnceleb recipe, and the results are listed as following:
ResNet34
> [feature] Add support score calibration

- docs/python_package.md
- wespeaker/cli/speaker.py
- wespeaker/cli/utils.py
- wespeaker/diar/extract_emb.py
- wespeaker/frontend/s3prl.py
add device option to wespeaker cli, for example, `--device mps` for Metal (MacOS) and `--device cuda` or `--device cuda:0` for CUDA (Windows and Linux)
set onnxruntime log level to 1 in extract_emb.py
> add device option in wespeaker cli; set onnxruntime log level

- examples/voxceleb/v2/conf/redimnet.yaml
- wespeaker/models/redimnet.py
- wespeaker/models/speaker_model.py
Add ReDimNet as mentioned in https://github.com/wenet-e2e/wespeaker/issues/341
> [feature] add redimnet

- wespeaker/dataset/processor.py
`tarfile` may have error `AttributeError: '_Stream' object has no attribute 'seekable'`. This updated syntax will fix this error.
> [fix] fix tarfile bug in processor.py

- wespeaker/cli/speaker.py
By returning an empty list in cli.speaker.Speaker.diarize if VAD returns an empty list. Otherwise a call results in this error:
```
File "/usr/local/lib/python3.9/site-packages/wespeaker/cli/speaker.py", line 252, in diarize
embeddings = self.extract_embedding_feats(subseg_fbanks,
File "/usr/local/lib/python3.9/site-packages/wespeaker/cli/speaker.py", line 111, in extract_embedding_feats
fbanks_array = np.stack(fbanks)
File "/usr/local/lib/python3.9/site-packages/numpy/core/shape_base.py", line 445, in stack
raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```
> Avoid error when attempting to diarize audio with no speech
